remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: Occupation, Apartheid, and Genocide
description: How the (im)mobility of people, ideas, and arms implicates us in the ongoing Nakba
